---
- name: Copy dump
  hosts: MariaDBReplica
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/mariaDB/mariaDB.yml

  tasks:
    - name: Change primary to primary server 192.168.31.46 and use binary log 'mysql-bin.000001' with position 1440
      community.mysql.mysql_replication:
        mode: changeprimary
        login_unix_socket:
          /var/lib/mysql/mysql.sock
        login_user: root
        login_password:
          "{{ mariaDBSlave_root_password }}"
        primary_host: 192.168.31.46
        primary_user: "{{ repl_user_name }}"
        primary_password: "{{ repl_user_password }}"
        primary_log_file: mysql-bin.000001
        primary_log_pos: 3135