---
- name: Copy dump
  hosts: MariaDBMaster
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/mariaDB/mariaDB.yml

  tasks:
    - name: Get primary binlog file name and binlog position
      community.mysql.mysql_replication:
        login_unix_socket:
          /var/lib/mysql/mysql.sock
        login_user: root
        login_password:
          "{{ mariaDBMaster_root_password }}"
        mode: getprimary