---
- name: Install maria DB
  hosts: MariaDBReplica
  remote_user: root

  tasks:
    - name: Connect repository
      ansible.builtin.get_url:
        url: 'https://downloads.mariadb.com/MariaDB/mariadb_repo_setup'
        dest: /tmp/

    - name: Mariadb_repo_setup
      ansible.builtin.shell:
        bash /tmp/mariadb_repo_setup --mariadb-server-version=10.9

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: MariaDB-server, MariaDB-client, MariaDB-backup
        state: latest

    - name: Enable and started MariaDB
      ansible.builtin.systemd:
        name: mariadb.service
        state: started
        enabled: true

    - name: Copy config
      ansible.builtin.copy:
        src: /home/zooloo/Dropbox/andibleGitHub/ansible/files/mariaDB/conf/slave/my.cnf
        dest: /etc/my.cnf
      notify: restart MariaDB

    - name: Install python3-mysqlclient
      ansible.builtin.dnf:
        name: python3-PyMySQL # python3-mysqlclient
        state: latest

  handlers:
    - name: Restart MariaDB
      ansible.builtin.systemd:
        name: mariadb.service
        state: restarted