---
- name: Create test database
  hosts: MariaDBMaster
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/mariaDB/mariaDB.yml

  tasks:
    - name: Create new databases with names 'foo' and 'bar'
      community.mysql.mysql_db:
        login_unix_socket:
          /var/lib/mysql/mysql.sock
        login_user:
          root
        login_password:
          "{{ mariaDBMaster_root_password }}"
        name:
        - foo1
        - bar2
        state: present