---
- name: Create maria DB replication user
  hosts: MariaDBMaster
  remote_user: root

  tasks:
    - name: Install python3-mysqlclient
      ansible.builtin.dnf:
        name: python3-mysqlclient
        state: present

    - name: Create database user
      community.mysql.mysql_user:
        name: repl_user
        password: k7LicUhZ9mKjXCyJqIAgJUSyT8BEEB9JEu9
        priv: "*.*:REPLICATION CLIENT"
        state: present