---
- name: Create dump
  hosts: MariaDBMaster
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/mariaDB/mariaDB.yml

  tasks:
    - name: Secure mariadb
      become: true
      expect:
        command: mysql_secure_installation
        responses:
        'Enter current password for root': ''
        'Set root password': 'y'
        'Remove anonymous users': 'y'
        'Disallow root login remotely': 'y'
        'Remove test database': 'y'
        'Reload privilege tables now': 'y'
        timeout: 1