---
- name: Amavisd DKIM generation
  hosts: mailWZ
  remote_user: hd
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/service/main.yaml

  tasks:
    - name: Generation pem file
      ansible.builtin.shell: sudo amavisd -c /etc/amavisd/amavisd.conf genrsa /var/lib/dkim/{{ domainName }}.pem 1024

    - name: Change chown
      become: true
      ansible.builtin.file:
        path: /var/lib/dkim/{{ domainName }}.pem
        owner: amavis
        group: amavis
        state: touch
        mode: 400