all:
  children:
    test:
      hosts:
        testVPS:
          ansible_host: 192.168.31.17
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
        testVPSAlma:
          ansible_host: 192.168.31.46
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
        testVPSAlmaReplica:
          ansible_host: 192.168.31.213
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
          ansible_python_interpreter: "/usr/bin/python3"

    MariaDBMaster:
      hosts:
        testVPSAlma:
          ansible_host: 192.168.31.46 
          ansible_port: 22 
          ansible_user: root 
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
          ansible_python_interpreter: "/usr/bin/python3"

    MariaDBReplica:
      hosts:
        testVPS:
          ansible_host: 192.168.31.17
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub

        testVPSAlmaReplica:
          ansible_host: 192.168.31.213
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub