all:
  children:
    test:
      hosts:
        testVPS:
          ansible_host: 192.168.31.17
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519
        testVPSAlma:
          ansible_host: 192.168.31.47
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
        testVPSAlmaReplica:
          ansible_host: 192.168.31.213
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
          ansible_python_interpreter: "/usr/bin/python3"
        testVPSAnsible:
          ansible_host: 192.168.31.224
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
          ansible_python_interpreter: "/usr/bin/python3"

    MariaDBMaster:
      hosts:
        testVPSAlma:
          ansible_host: 192.168.31.47
          ansible_port: 22 
          ansible_user: root 
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub
          ansible_python_interpreter: "/usr/bin/python3"

    MariaDBReplica:
      hosts:
        testVPS:
          ansible_host: 192.168.31.17
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519

        testVPSAlmaReplica:
          ansible_host: 192.168.31.213
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub

    proxmox:
      hosts:
        proxmoxWW:
          ansible_host: 167.235.180.81
          ansible_port: 22
          ansible_user: 'root'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/id_ed25519.pub

    webzilla:
      hosts:
        mailWZ:
          ansible_host: 78.140.179.180
          ansible_port: 22
          ansible_user: 'hd'
          ansible_ssh_private_key_file: /home/zooloo/.ssh/hd-wzilla