---
- name: Install maria DB 
  hosts: test
  remote_user: root

  tasks:
    - name: connect repository
      ansible.builtin.get_url:
        url: 'https://downloads.mariadb.com/MariaDB/mariadb_repo_setup'
        dest: /tmp/

    - name: mariadb_repo_setup
      ansible.builtin.shell:
        bash /tmp/mariadb_repo_setup --mariadb-server-version=10.9

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: MariaDB-server, MariaDB-client, MariaDB-backup
        state: latest

    - name: enable and started MariaDB
      ansible.builtin.systemd:
        name: mariadb.service
        state: started
        enabled: yes

    - name: copy config
      ansible.builtin.copy:
        src: mariadb/master/my.cnf
        dest: /etc/my.cnf
      notify: restart MariaDB

  handlers:
    - name: restart MariaDB
      ansible.builtin.systemd:
        name: mariadb.service
        state: restarted