---
- name: Install php - 8.2 version
  hosts: test
  remote_user: root

  tasks:
  - name: install epel-release
    ansible.builtin.dnf:
      name: epel-release
      state: latest

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      state: present
      
  - name: install remi
    ansible.builtin.dnf:
      name: 'http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm'
      state: present
      
  - name: install yum-utils
    ansible.builtin.dnf:
      name: epel-release
      state: latest

  - name: install dnf-utils
    ansible.builtin.dnf:
      name: dnf-utils
      state: latest

  - name: install php:remi-8.2
    ansible.builtin.dnf:
      name: php:remi-8.2
      state: latest
      
  - name: install php-8.2
    ansible.builtin.dnf:
      name: php
      state: latest
