---
- name: Copy new config
  gather_facts: false
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/php-fpm/php-fpmVars.yml

  tasks:
  - name: Copy file nginx.conf
    ansible.builtin.copy:
      src: "{{ newConfPath }}"
      dest: /etc/nginx/conf.d/

  - name: Copy file www.conf
    ansible.builtin.copy:
      src: "{{ ConfPathWwwConf }}"
      dest: /etc/php-fpm.d/

  - name: Copy file index.html
    ansible.builtin.copy:
      src: "{{ newIndexPath }}"
      dest: /var/www/html/

    notify:
      - Restart php-fpm

  - name: Restart nginx
    ansible.builtin.shell: |
      systemctl restart nginx

  handlers:
    - name: Restart php-fpm
      ansible.builtin.systemd:
        name: php-fpm
        state: restarted
        enabled: yes