---
- name: Install php - 8.2 version
  hosts: test
  remote_user: root

  tasks: 
    - name: Adding Remi repo pgp keys
      ansible.builtin.get_url:
        url: https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el9
    
    - name: Add remi repo 
      yum_repository: 
        name: remi
        description: Remi repo for Enterprise Linux 9
        mirrorlist: http://cdn.remirepo.net/enterprise/9/remi/$basearch/mirror
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el9

    - name: Add remi-modular repo
      yum_repository:
        name: remi-modular
        description: Remi's Modular repository for Enterprise Linux 9 - $basearch
        mirrorlist: http://cdn.remirepo.net/enterprise/9/modular/$basearch/mirror
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el9

    - name: Adding remi-safe repo
      yum_repository:
        name: remi-safe 
        description: remi safe repository for Enterprise Linux 9 - $basearch
        mirrorlist: http://cdn.remirepo.net/enterprise/9/modular/$basearch/mirror
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el9

    - name: install dnf-utils
      ansible.builtin.dnf:
        name: dnf-utils
        state: latest

    - name: Enable php 8.2 remi repo
      ansible.builtin.shell: dnf module enable php:remi-8.2 -y

    - name: install php-8.2
      ansible.builtin.dnf:
        name: php
        state: latest

      notify: Start and enable php-8.2

  handlers:
    - name: Start and enable php-8.2
      ansible.builtin.systemd:
        name: php-fpm
        state: started
        enabled: yes