---
- name: Prepair new test host after Install
  hosts: restore-bareos
  remote_user: root

  tasks:
    - name: Install mc is at the latest version
      ansible.builtin.dnf:
        name: mc
        state: latest

    - name: Install zsh is at the latest version
      ansible.builtin.dnf:
        name: zsh
        state: latest

    - name: Install git is at the latest version
      ansible.builtin.dnf:
        name: git
        state: latest

    - name: Install vim is at the latest version
      ansible.builtin.dnf:
        name: vim
        state: latest

    - name: Firewalld disable
      ansible.builtin.systemd:
        name: Firewalld
        state: stopped
        enabled: false