---
- name: Security package update
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/service/main.yaml

  tasks:
  - name: Check update
    ansible.builtin.dnf:
      name: "*"
      state: latest
      security: true