---
- name: Security update check count
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/service/main.yaml

  tasks:
  - name: Copy securityUpdateCheck.sh
    ansible.builtin.copy:
      src: "{{ shPathSecUpdChk }}"
      dest: /tmp/

  - name: Start securityUpdateCheck.sh
    ansible.builtin.shell: |
      sh /tmp/securityUpdateCheck.sh

  - name: Remove securityUpdateCheck.sh
    ansible.builtin.shell: |
      rm -f /tmp/securityUpdateCheck.sh