---
- name: User create
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/service/main.yaml

  tasks:
  - name: Copy users.sh
    ansible.builtin.copy:
      src: "{{ shPath }}"
      dest: /tmp/

  - name: Start users.sh
    ansible.builtin.shell:
      sh /tmp/users.sh

  - name: Remove users.sh
    ansible.builtin.shell:
      rf /tmp/users.sh