---
- name: Create temlate from VMManager 6
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/service/main.yaml

  tasks:
  - name: Xz packing
    community.general.archive:
      path:
        - /home/hd/almaQcow.qcow
      format: xz