---
- name: Create dump
  hosts: MariaDBMaster
  remote_user: root

  tasks:
    - name: Dump databases to testVPSAlma.sql
      community.mysql.mysql_db:
        login_user: root
        login_password: 1sp8yjELann29RWmC4Et
        state: dump
        name: foo, bar
        target: /tmp/dump.sql.gz
        pipefail: true