---
- name: Copy new config
  gather_facts: false
  hosts: test
  remote_user: root
  vars_files: /home/zooloo/Dropbox/andibleGitHub/ansible/vars/nginx/nginxVars.yml

  tasks:
  - name: Copy file nginx.conf
    ansible.builtin.copy:
      src: "{{ newConfPath }}"
      dest: /etc/nginx/conf.d/

  - name: Copy file index.html
    ansible.builtin.copy:
      src: "{{ newIndexPath }}"
      dest: /usr/share/nginx/html/

    notify: Start and enable nginx

  handlers:
    - name: Start and enable nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
