services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

  php:
    image: php:8.1-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html/

  app-data:    
    image: php:8.1-fpm
    container_name: app-data-container  
    volumes:  
      - ./www/html/:/var/www/html/  
    command: "true"

  mysql:    
    image: mysql:5.7  
    container_name: mysql-container  
    volumes_from:  
      - mysql-data  
    environment:  
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password  

  mysql-data:    
    image: mysql:5.7  
    container_name: mysql-data-container  
    volumes:  
      - /var/lib/mysql  
    command: "true"