---
- name: Install postgreSQL
  hosts: almaPG
  remote_user: root

  tasks:
    - name: Create the databases
      community.postgresql.postgresql_db:
        name: "TestBase"
        encoding: "UTF-8"
      become: true
      become_user: postgres

    - name: Create the users
      community.postgresql.postgresql_user:
        db: "TestBase"
        name: "Ololosh"
        password: "Ololosh!dsFD_2er2"
      become: true
      become_user: postgres
      environment:
        PGOPTIONS: "-c password_encryption=scram-sha-256"

    - name: "Grant db user access to app db"
      community.postgresql.postgresql_privs:
        type: database
        database: "TestBase"
        roles: "Ololosh"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/pgsql/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "Ololosh"
        create: true
      become: yes
      become_user: postgres
      notify: Restart postgres

  handlers:
    - name: Restart postgres
      ansible.builtin.systemd:
        name: postgresql.service
        state: restarted