---
- name: Install postgreSQL
  hosts: bareos.pve.zooloo.home
  remote_user: root

  tasks:
    - name: Install postgreSQL
      ansible.builtin.dnf:
        name: postgresql, postgresql-server, python3-psycopg2
        state: latest
        update_cache: true

    - name: Create the cluster
      ansible.builtin.command:
        cmd: postgresql-setup initdb
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Start and enable the service
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true